### ISSUE TITLE
Update Examples to 0.6.

### ISSUE THREAD

**Issue by sabel83** [klemens-morgenstern/boost-process#11] opened 2016-06-21 20:32 UTC
I've tried to build and run `example/async_io.cpp`. I use a Hello World application as the child process, which terminates after displaying `Hello World`. The example app (`async_io.cpp`) hangs for ever.

I'm testing on Ubuntu 14.04 with g++ 4.8.5 and I'm using this library together with Boost 1.61.0.

**Comment by klemens-morgenstern** [comment] 2016-06-21 20:40
Thanks for the report and for testing the library. That is a known issue, inhertied from boost.proces 0.5 - I'll add 0.6 examples soon, sry for that - I just changed them so they compile. 
The Problem is: the pipe is not closed on the exit of the child process, therefor it won't exit properly.

You can do one of the following things in order to fix it:

```cpp
    boost::asio::io_service ios;
    boost::process::async_pipe p(ios);

    child c(
        "test.exe",
        std_out > ios,
        ios, //to get on_exit to work
        on_exit([&](int, const std::error_code& ec)
        {
               ios.post([&]{p.close();}); //so the current async operation finishes.
         })
    );
```

@BorisSchaeling

**Comment by klemens-morgenstern** [comment] 2016-06-21 20:43
Other Variant is to let the library do the whole async-pipe implicitly like this:

```
std::vector<char> buf;
boost::asio::io_service ios;

child c(
        "test.exe",
        std_out > asio::buffer(buf),
        ios);

```

**Comment by sabel83** [comment] 2016-06-21 20:53
If I understand correctly, the `on_exit`-based solution will close the pipe on my (the parent process) end when the child terminates. Isn't there a race condition? What happens if the child writes a large amount of data to the pipe and terminates before the parent process using your library would read all of it? (assuming that the next async read operation can't get it all, so we would have to keep reading).

Do you close the writing side of the pipe in the parent process after launching the child? (It should be done, but it is not clear to me based on your API which element's responsibility is that - the constructor of `child`?)

**Comment by sabel83** [comment] 2016-06-21 21:00
Additional info: I'm trying to replace my own child process management library (https://github.com/sabel83/just/blob/master/include/just/process.hpp) with yours (mainly to have more control over the child process and be able to interact more with the child instead of reading the whole output together) Capturing stdout/stderr works there on Linux/Windows/OSX, so you can see what I'm trying to achieve.

**Comment by klemens-morgenstern** [comment] 2016-06-21 21:01
Now, the io_service waits for the child process to exit and thus will close the pipe when the child exits.
If I would close the pipe directly, it would immediately stop the I/O operation, which is why it is posted to the io-service.
But: you are right, that this might still cause a data-loss, if the buffer is sufficiently large. This case might be rare, but it is not impossible.
There is however not solution to this, other than to either implement a timer (which you could do with boost.asio) or the actually know the structure of the output data and then to use `boost::asio::async_read_until`.

**Comment by klemens-morgenstern** [comment] 2016-06-21 21:07
Awesome! That'd be great, If I understand your interface correctly (from the readme.md) you could just write this :

```
template <class Seq>
just::process::output process::run(const Seq& cmd_, const std::string& input_)
{
      vector<const char*> cmd(cmd_.size() + 1, 0);
      transform(cmd_.begin(), cmd_.end(), cmd.begin(), impl::c_str);
      
      vector<char> out;
      vector<char> err;
      auto exit = system(cmd, std_in<buffer(input_), std_out>out, std_err>err);
    
      return output(exit, string(out.begin(), out,end()), string(err.begin(), err.end());     
}
```

**Comment by sabel83** [comment] 2016-06-21 21:08
Pipes have two ends: a writing and a reading end (two file descriptors). When you create the pipe, you have both (check http://linux.die.net/man/2/pipe for example). The child needs to get the writing end (in case of stdout/stderr), so after forking you can close the reading side in the child. Also, after forking you should close the writing side in the parent, otherwise you won't see the EOF on the reading side when the child dies (as the pipe remains open, since there is a process - the parent - keeping the writing end open).

**Comment by klemens-morgenstern** [comment] 2016-06-21 21:10
It's not that easy, in order to implement asynchronous pipes I use named pipes on windows. They Do now behave as file-handles, hence they don't really have a sink and source-handle. Thus I cannot detect via the pipe that the child has exited. And since I want consistency, I want to have the same behaviour on posix.

**Comment by sabel83** [comment] 2016-06-21 21:11
Yes, I could do that, but:

1. I'm concerned about loosing data because of the pipe closing issue (I'm about to run processes dumping out a lot of data and terminating) described above

2. My goal with moving to your library is to get access to the pipes and be able to interact more with the process while it is running (so the simplified API won't work for me - I can get that with my own lib as well).

**Comment by sabel83** [comment] 2016-06-21 21:15
Why do you use named pipes?

**Comment by klemens-morgenstern** [comment] 2016-06-21 21:15
1. Ok, well I cannot cover that in boost.process, because there are to many way to do that. Boost.asio might give you a solution, and that integrates well with boost.process. You do not need to be too worried though, since buffer sizes are usually not that huge. Your chlid process will not exit until every data byte is written into the buffer
You could of course just keep the pipe open much longer than the chlid is alive or set a timer - won't cost you perfomance since you already use boost.asio there.

2. Yep, that was a replacement, of course.

**Comment by klemens-morgenstern** [comment] 2016-06-21 21:16
Well, I need to use them with boost.asio (i.e. for the `async_pipe` not the regular one) and to provide async operations on windows, you need the whole OVERLAPPED stuff and that's not provided for unnamed pipes. Thus: named pipes if you go async.

**Comment by klemens-morgenstern** [comment] 2016-06-21 22:09
Alright I changed the example and updated a bit of the doc, so I'll close the issue now. I can only recommend you look into boost.asio, that library is just awesome.
If you have any question, feel free to write me an E-Mail or write me on gitter.

**Closed by klemens-morgenstern** 2016-06-21 22:09 UTC
