### ISSUE TITLE
two children with closed pipes hang causes wait_for to timeout and return false

### ISSUE THREAD

**Issue by mats-johnson** [klemens-morgenstern/boost-process#224] opened 2020-11-15 17:25 UTC
Perhaps this has the same underlying cause. If I close the pipes to both child processes, neither will terminate. If I call child::terminate() on one of them, then both stops.

boost 1.73, clang 11, Red Hat Enterprise Linux Server release 7.7 (Maipo)

Replicating program prints this:
```
   create a
   create b
   close a
   close b
   wait for a
      did not terminate
   wait for b
      did not terminate
terminate a
   wait for a
      terminated
   wait for b
      terminated

```
```
#include <iostream>
#include <boost/filesystem.hpp>
#include <boost/process.hpp>
#include <chrono>

using namespace std;
using namespace std::chrono;
using boost::filesystem::path;
namespace bp = boost::process;

static duration const timeout = seconds(5);

void close(bp::opstream& op, string name) {
    cout << "   close " << name << "\n";
    op.close();
    op.pipe().close();
}

void wait_for(bp::child& c, string name) {
    cout << "   wait for " << name << "\n";
    auto t1 = high_resolution_clock::now();
    if (c.wait_for(timeout)) {
        auto t2 = high_resolution_clock::now();
        auto duration = duration_cast<seconds>( t2 - t1 ).count();
        if (duration > 0)
            cout << "      terminated after " << duration << "s\n";
        else
            cout << "      terminated\n";
    } else {
        cout << "      did not terminate\n";
    }
}

bp::child create(bp::opstream& p, string name) {
    cout << "   create " << name << "\n";
    path cat = bp::search_path("cat");
    string f = name + ".txt";
    return bp::child(cat, "-", bp::std_in < p, bp::std_out > f, bp::std_err > stderr);
    p << "Hello world!\n";
}

int main(int argc, char** argv) {
    bp::opstream a, b;
    bp::child a_child = create(a, "a");
    bp::child b_child = create(b, "b");
    close(a, "a");
    close(b, "b");
    // Here I expect both a and b to terminate since their pipes
    // are closed
    wait_for(a_child, "a");
    wait_for(b_child, "b");
    // but, neither of them terminates
    // When one is terminated, the other one terminates as well
    cout << "terminate a\n";
    a_child.terminate();
    // now both are "<defunct>" since not waited for yet
    wait_for(a_child, "a");
    wait_for(b_child, "b");
}

```

**Comment by klemens-morgenstern** [comment] 2022-06-11 05:49
Loosk like a duplicate of #223

**Closed by klemens-morgenstern** 2022-06-11 05:49 UTC
