### ISSUE TITLE
Should I use one io_service per child process?

### ISSUE THREAD

**Issue by koskokos2** [klemens-morgenstern/boost-process#109] opened 2017-07-21 12:29 UTC
[Example from mailing lists](https://lists.boost.org/boost-users/2017/07/87703.php) shows that on_exit callbacks vector is shared across multiple child processes if they using same io_service instance. So wrong process can call on_exit callback set for other child process. Is this intended behaviour and io_service instance should not be shared across multiple child processes or there is a way to handle this case?

**Comment by klemens-morgenstern** [comment] 2017-07-21 13:08
That's the first time I see this example and it seems like a strange to approach this (i.e. calling yourself).
The on_exit should not be shared across processes, though that might happen since the child-signal could lead to this. Not sure, this shared behaviour is not intended though.

**Comment by sandym** [comment] 2017-07-21 13:18
I just did the 'calling yourself' thing so that I can try the same example on Windows, replace with /bin/sleep if you like. Same problem as the last comment in issue #104, on_exit callback are not associated with the child they are set on.

**Comment by sandym** [comment] 2017-07-21 14:01
Here's the same example, with a different run loop at the end. As soon as c1 exit, both c1.running() and c2.running() return false, even if c2 terminate 2 seconds later (and call the c1 callback).

I don't have a test case for that, but I also had problem with stderr/stdout capture mixing up when handling multiple child processes.  It would seems that this library is limited to managing one single child process for now, which makes it a lot less useful.

```

#include <boost/process.hpp>
#include <boost/asio.hpp>
#include <thread>
#include <iostream>

int main( int argc, char **argv )
{
    if ( argc > 2 && strcmp( argv[1], "sleep" ) == 0 )
    {
        auto s = atoi(argv[2]);
        std::cout << (s/2) << "- about to sleep for " << s << "s" << std::endl;
        std::this_thread::sleep_for( std::chrono::seconds(s) );
        std::cout << (s+1) << "- finish sleeping for " << s << "s" << std::endl;
        return 0;
    }
    
    namespace bp = boost::process;
    boost::asio::io_service ios;
    
   // launch a child that will sleep for 2s
    auto c1 = bp::child( argv[0], "sleep", "2", ios,
                                   bp::on_exit( [](int, const std::error_code&)
                                   { std::cout << "4- sleep 2s child finished" << std::endl; }) );
                                   
    // wait a bit, make sure the child launch for my test
    std::this_thread::sleep_for( std::chrono::milliseconds(10) );
    
   // launch a child that will sleep for 4s
    auto c2 = bp::child( argv[0], "sleep", "4", ios,
                                   bp::on_exit( [](int, const std::error_code&)
                                   { std::cout << "6- sleep 4s child finished" << std::endl; }) );
                                   
    // wait for the notifications
    while ( not ios.stopped() )
    {
		std::cout << "c1: " << c1.running() << std::endl;
		std::cout << "c2: " << c2.running() << std::endl;

	    ios.run_one();
	}
}

```

**Comment by klemens-morgenstern** [comment] 2017-07-21 15:14
Well first of all, I feel horrible I haven't solved that yet. Could you be so kind and test if it works when you run it on different io_services? I fear it's a problem with `boost::asio::signal_set` though.

**Comment by egorpugin** [comment] 2017-07-21 16:14
Isn't it possible to bind that callback to specific child (as io object) using asio stuff?

**Comment by klemens-morgenstern** [comment] 2017-07-21 16:16
Yeah it uses [`signal_set`](http://www.boost.org/doc/libs/1_64_0/doc/html/boost_asio/reference/signal_set.html) under the hood - which might be the problem and why it works on windows. BEcause on windows it wait's for a specific object.

**Comment by sandym** [comment] 2017-07-21 22:36
I tried using 2 io_services as @kkk777kkk suggested, one for each of c1 and c2 and replacing the run loop at the end with:

```
while ( not ios1.stopped() or not ios2.stopped() )
{
        ios1.poll();
        ios2.poll();
}

```

same result. I haven't tried using a dedicated thread for each io_service.run().

Great API by the way, it was a charm to use for process management and a big disappointment when it started to fail in deployment where our application is used to manage many processes.

**Comment by klemens-morgenstern** [comment] 2017-07-22 06:03
Yeah, that's a horrible bug, I hear you.
I fear what I'll actually need to do is have a single `signal_set` running and checking which one terminated through  `waitpid`. Which is bad because it uses a global `signal_set`, but not really avoidable on posix.

**Comment by egorpugin** [comment] 2017-07-23 15:09
I've prepared a patch for this.
@klemens-morgenstern, please, check and commit if you think it's correct.

Explanations:
1. [signal_set](http://www.boost.org/doc/libs/1_64_0/doc/html/boost_asio/reference/signal_set.html) page says:
```
Multiple registration of signals
The same signal number may be registered with different signal_set objects. When the signal occurs, one handler is called for each signal_set object.
```
So, it's possible to have multiple `signal_set`s, io service will try them all.
2. We can ignore wrong callbacks comparing pid of died child using `waitpid`. Call new `async_wait` in case it's not our expected child.
3. Callback is set now `on_success` because we must know pid of the child. `on_error` is removed because signal is not set to this moment, we don't need unset anything.

Files in attached archive:
`demo.patch` - patch with some debug stdout messages.
`real.patch` - ready to apply.
`bp.cpp` - example from https://github.com/klemens-morgenstern/boost-process/issues/109#issuecomment-317009152
`bp2.cpp` - example with two io_services.
`bp2t.cpp` - two io_services running in two different threads.

You can consider these examples as tests for you test suite.

With my patch I see following output:
```
1- about to sleep for 2s
2- about to sleep for 4s
3- finish sleeping for 2s
4- sleep 2s child finished
// not my business <- this will be shown with debug patch

5- finish sleeping for 4s
6- sleep 4s child finished
```

[fix.zip](https://github.com/klemens-morgenstern/boost-process/files/1168163/fix.zip)

**Comment by klemens-morgenstern** [comment] 2017-07-23 15:36
@egorpugin Thanks man, that's awesome! 
If could fork the library and put it into a PR (using sparring_partner for the test, was wait.cpp does) I'd love to merge it. Not only because I'm lazy, but also bc you'd be properly credited on github as a contributor. If not, I'll do that sometime next week.

**Comment by egorpugin** [comment] 2017-07-23 15:51
Ok, will try to do it.
I just was a bit scarried of boost.test (did not run it ever). :)

**Comment by klemens-morgenstern** [comment] 2017-07-23 15:52
Ah ok, if you want to run a local build, replace the libs/process with your working version in the boost directory and run b2 from the test file. That should do it. And be more scared of boost.build, boost.test is easy ;):

**Comment by sandym** [comment] 2017-07-24 07:23
I tried the patch, it does work as expected in the my test code.

If I replace the final run loop (ios.run();) with the following code:

```
    while ( not ios.stopped() )
    {
        //c1.running();
        ios.run_one();
    }

```
 It still work, basically I run the event handler one by one for as long as there is work to do. This will correctly terminate once all child processes finish and all on_exit are called.

But if I uncomment the c1.running() line, I get an infinite loop and I'm missing one callback, that is the  fact of asking if a child is still running while the loop is running screw up the events.

**Comment by egorpugin** [comment] 2017-07-24 08:04
Yes, I also see some such side effects.
Investigating.

**Comment by egorpugin** [comment] 2017-07-24 09:18
So, it seems when you provide io service + on_exit callback you cannot run sync code anymore (c.wait(), c.running()).

**Comment by klemens-morgenstern** [comment] 2017-07-24 10:11
That should work, the actual exit-code is stored in a shared_ptr so the first one catching the exit registers that. But there could be a race condition I missed.

**Comment by egorpugin** [comment] 2017-07-24 10:31
The issue is that you can query waitpid from the system only once. But all those functions .running(), .wait(), signal_set.async_wait() use it.
So once first call is done with zombie process destroyed, we can't do that anymore and async case fails completely.
Probably it would be nice to add a member var called _exited, so all these functions will check it first, so the logic won't be broken very much.

**Comment by klemens-morgenstern** [comment] 2017-07-24 12:21
That's sort of done [here](https://github.com/klemens-morgenstern/boost-process/blob/develop/include/boost/process/detail/child_decl.hpp#L52)
I'd think that all the other `waitpid` would fail, thus the result is shared. But again: I might have missed a race-condition.

**Comment by egorpugin** [comment] 2017-07-24 12:42
Yes, but only sort of.
detail::is_running() still calls waitpid every time.
With grep I see:
```
$ grep -r "::waitpid" .
./io_service_ref.hpp:            int ret = ::waitpid(pid, &status, WNOHANG);
./is_running.hpp:    auto ret = ::waitpid(p.pid, &status, WNOHANG|WUNTRACED);
./is_running.hpp:    auto ret = ::waitpid(p.pid, &status, WNOHANG|WUNTRACED); 
./terminate.hpp:    ::waitpid(p.pid, &status, 0); //just to clean it up
./terminate.hpp:    ::waitpid(p.pid, &status, 0); //just to clean it up
./wait_for_exit.hpp:        ret = ::waitpid(p.pid, &status, 0);
./wait_for_exit.hpp:        ret = ::waitpid(p.pid, &status, 0);
./wait_for_exit.hpp:        ret = ::waitpid(p.pid, &status, WUNTRACED | WNOHANG);
./wait_for_exit.hpp:        ret = ::waitpid(p.pid, &status, WUNTRACED | WNOHANG);
./wait_for_exit.hpp:        ret = ::waitpid(p.pid, &status, WUNTRACED | WNOHANG);
./wait_for_exit.hpp:        ret = ::waitpid(p.pid, &status, WUNTRACED | WNOHANG);
./wait_group.hpp:        ret = ::waitpid(-p.grp, &status, 0);
./wait_group.hpp:        ret = ::waitpid(-p.grp, &status, 0);
./wait_group.hpp:        ret = ::waitpid(-p.grp, &status, WUNTRACED | WNOHANG);
./wait_group.hpp:        ret = ::waitpid(-p.grp, &status, WUNTRACED | WNOHANG);
./wait_group.hpp:        ret = ::waitpid(-p.grp, &status, WUNTRACED | WNOHANG);
./wait_group.hpp:        ret = ::waitpid(-p.grp, &status, WUNTRACED | WNOHANG);
```

Excluding wait_group calls - 11 places.
From my pov there should be only one place with such structure:

```
struct pid_handle
{
  pid_t pid;
  int status;

  bool exited()
  {
    if (_exited) return true;
    waitpid(...) // a single place!
    ...
  }

private:
  bool _exited = false;
};
```

This structure (one per child) must be available to all other internal stuff to be reusable.

**Comment by klemens-morgenstern** [comment] 2017-07-24 13:04
Well the one in `io_service_ref` is to obtain the exit-code after the signal (and to remove the zombie), terminate is also for the latter, and the six in ` wait_for_exit` are for `wait`, ` wait_for`, `wait_until` in one variant with exception, the other with ` std::system_error`. So that seems quite correct to me.

**Comment by amerry** [comment] 2018-02-22 13:40
I believe #145 should fix this.

**Comment by klemens-morgenstern** [comment] 2022-06-11 05:27
This whole on_exit design was a mistake.

I just merged v2 in boostorg/process, that will treat the process as an io-object.

I'll move all the issue handling to boostorg/process, please reopen the issue there.

**Closed by klemens-morgenstern** 2022-06-11 05:27 UTC
