### ISSUE TITLE
Cannot get exit code after calling terminate()

### ISSUE THREAD

**Issue by amerry** [klemens-morgenstern/boost-process#149] opened 2018-02-22 11:38 UTC
If you call `terminate()` on a `child` instance, the exit status is not recorded - the code seems to assume you will not do anything further with the child instance other than assign to it or destroy it. However, the documentation doesn't suggest that this would be the case.

However, if you call `terminate()` on a `group`, you can still wait on its children (at least on posix).

Is this the intended behaviour? I'm happy to do a merge request, but I'm not sure whether I should be changing the code or the documentation.

**Comment by klemens-morgenstern** [comment] 2018-02-22 12:13
That should not be the behaviour of a group, terminating that should reap the children actually. 
Calling terminate on a subprocess would result in an invalid exit-code, because you can actually set it in on windows [see here](https://msdn.microsoft.com/de-de/library/windows/desktop/ms686714(v=vs.85).aspx), which is why I just considered that invalid and ignore it. Btw. the groups are (still and to my shame) broken on windows.

**Comment by amerry** [comment] 2018-02-22 13:33
Killing a process via a signal on posix also produces an exit code not under the control of the terminated process, so it's not really unique to Windows.

This doesn't change the fact that you can call `TerminateProcess()`/`::kill()` without using the `terminate()` method of `child` (or `group`), and you *will* get the exit code. I don't really see why calling the `terminate()` method should give you different behaviour, but it's not that big a deal (if you're calling terminate, you can deal with the consequences via external state) as long as it's documented.

It's also worth noting how the async on_exit handler behaves. On posix, at least, it will trigger when you call `terminate()`, and report an error ("No child processes"). I haven't tried on Windows yet.

**Comment by klemens-morgenstern** [comment] 2018-02-22 14:08
Fair enough, I just decided to go with "didn't exit properly, thus not exit-code" as my design choice. Doesn't mean that's the best one.

What you're definitely right about is the `on_exit` behavior when terminate is called - what would you propose? Having an exit_code passed to the handler that indicates a terminate or an `error_code` that does the same?

**Comment by amerry** [comment] 2018-02-22 14:38
`boost::asio::errors::operation_aborted` would be an OK choice for the error, I think - it feels right to treat it like cancelling the operation.

**Comment by klemens-morgenstern** [comment] 2018-02-22 14:42
That seems write - how would you tread a wait then? I.e. if one thread calls `wait` another calls `terminate`, should `wait` throw a  `system_error` ?

**Comment by amerry** [comment] 2018-02-22 15:40
For consistency, I think it would be nice to do the same thing, yes - throw a `system_error` with a `boost::asio::errors::operation_aborted`.

**Comment by keith-bennett-gbg** [comment] 2018-02-22 17:08
As a user, my thoughts on getting child processes' statuses:

If I created a child process, I should always be able to retrieve its exit reason, no matter for what reason it exited. If I told it to terminate, I should be informed that "yes it actually terminated" or "no, it successfully exited before the termination could be done". If it exited normally with a non-successful exit code, I should be able to know. If it is terminated because of a POSIX signal (or Windows killed it or whatever), I should be able to retrieve the terminating signal. Anything that does not allow me to do that is, in my opinion, designed wrong.

If reaping is to be done automatically, any reaped information should absolutely be made available to users' code.

If you have two threads of execution trying to reap the same process, that could be a design error on the user's side? Either `wait()` succeeds and `terminate()` indicates that the process no longer exists, or else `wait()` indicates that the process no longer exists and `terminate()` succeeded. Why would it indicate an aborted operation? The OS should be able to tell us what happened. Why not pass on the OS's error code?

**Comment by klemens-morgenstern** [comment] 2018-02-22 17:19
Because that's different on Windows and posix and this library aims to provide unified behaviour. The problem is that there is no error code for a termination, but that posix puts that into the exit-code, while windows does not, but gives an error-code when using `WaitForObject` as asio does. There is no way to not for certain that a windows process was terminated without the async wait as it is on linux. That's the main problem here and I do not know how to fix it. The `TerminateProcess` function lets you set the exit-code, but you could have a process returning the same code coincidentally, thus you never know for sure.

So I'm not sure how to design that properly, which is why I decided to just ignore it. And even if you remember that you (as in the C++ code using this library) called terminate, you don't know if any other location did that by directly accessing the winapi or if you killed from another application, e.g. the task manager.

I might of course be misunderstanding the winapi documentation, so please let me know if you know a good design idea.

**Comment by keith-bennett-gbg** [comment] 2018-02-22 17:43
I would certainly _hope_ that the C++ developer building an application would design their application well enough to know where and how they would terminate a child application.

On the other hand, if the user (the end-user) killed the application through task manager, then `bp::child::wait()` should reap the child as before and `bp::child::terminate()` should "fail" to terminate but should still be able to reap as before. Note that the failure to terminate is only a technicality: the `TerminateProcess()` function might fail but the end result is the same intention: the child no longer exists. No changes there that I can see.

To be fair, I haven't built anything against WinAPI for at least 5 years, so I'm a bit rusty there. However, my understanding of Windows `TerminateProcess()` is that it returns immediately (just like POSIX `kill()`). You could then use `WaitForSingleObject()` (or similar) to wait until the process has _actually_ exited (or you can hot-loop on `GetExitCodeProcess()` while it continues to return `STILL_ACTIVE`), and then you can still get its exit reason using `GetExitCodeProcess()`. The process is reaped when all handles to the process are closed (regardless of whether its exit code was retrieved or not). Since the underling object is a handle to the process, its exit reason should still be available to our `child` code.

Do I misunderstand it?

**Comment by amerry** [comment] 2019-03-22 11:03
While the code as it stands might make sense for synchronous code, it leads to a mess when writing async code (using asio) that uses both the on_exit handler and terminate().

On UNIX, I'm getting the on_exit handler called with an error code (ECHILD/No child processes), while on Windows it's called with no error code, and 1 as the exit status. This is causing the platform behaviour to be unnecessarily different, instead of making it the same.

**Comment by klemens-morgenstern** [comment] 2022-06-11 05:29
The issue should be fixed with the v2 redesign, which can be found on boostorg/process.

I am closing this issue because I'll archive the repository. Please reopen if you see the need over there.

**Closed by klemens-morgenstern** 2022-06-11 05:29 UTC
