### ISSUE TITLE
async_pipe::async_close does not really close the pipe

### ISSUE THREAD

**Issue by mika-fischer** [klemens-morgenstern/boost-process#49] opened 2017-01-16 17:16 UTC
I'm not sure if this is a bug or if I'm just doing something wrong...

Minimal example here: https://gist.github.com/mika-fischer/e308f93aa987a4d1d64b0024c7df316d

Basically, I'm spawning a child process with a pipe to the childs stdin and want to close this pipe, so that the child reading from stdin gets EOF. But this never happens...

**Comment by klemens-morgenstern** [comment] 2017-01-16 19:25
Danke fürs testen und die Info.

Der `child` destruktor ruft `terminate` auf, wenn Du nicht `wait` aufrufst (Grund sind sehr viele potentielle Deadlocks). Das könnte ein Grund sein. 

Andererseits könnte das ein Bug der `async_pipe` sein, was passiert denn mit der normalen `pipe`?

Was ich mich ein wenig frage ist wieso das Program überhaupt ausgeführt wird, es fehlt die exe. D.h. eigentlich müsstest Du 

 ``
bp::child child(`bp::exe"./vtest", bp::args= {"child"},
                    bp::std_in  < pipe,
                    bp::std_out > stdout,
                    bp::std_err > stderr,
                    bp::on_exit([&](int exit, std::error_code) {exit_code = exit;}),
                    ios);
```

schreiben.

**Comment by mika-fischer** [comment] 2017-01-16 23:32
1.) Do you even have to call wait when constructing the child with an asio::io_service?
2.) The exe thing doesn't seem to make a difference, i.e. if I add bp::exe("./vtest"), the result is the same.
3.) When going fully sync, i.e. with bp::pipe, and without the io_service, the result is also the same. The bp::pipe::close() does not propagate to the child process. I can post a sync example tomorrow..

**Comment by klemens-morgenstern** [comment] 2017-01-17 00:12
1) Ah yes you're of course right, my bad. Yeah that should actually work.

3) Well that seems important enough to have test for that. I just added one though (fc601c2e31509f76b9d2cf3344d59e42de6b3756) and it works on windows, but not on linux. Which are you working on? If it's linux, I can reproduce the bug, so I might fix that soon.

**Comment by klemens-morgenstern** [comment] 2017-01-17 00:27
Interestingly enough I can only reproduce the bug on Travis CI, not on my Debian VM. That's rather strange. I'll look into it, btw. if you could give me the generated output of your example, that would be awesome.

**Comment by mika-fischer** [comment] 2017-01-17 09:14
I'm working on Linux. There the output is
```% ./vtest                                                                                                                                                                                                                                                      -- INSERT --
[P] Started
[C] Started
[P] pipe is_open: 1
[P] Closing pipe...
[P] pipe is_open: 0
```
and then it hangs. I'll check on Windows.

**Comment by klemens-morgenstern** [comment] 2017-01-17 09:29
Alright, that'll need some more attention, seems to be a linux bug. And a rather surprising one at that. I think I'll find the time to fix this on the weekend.

**Comment by mika-fischer** [comment] 2017-01-17 09:39
On Windows, things work as expected:
```[P] Started
[C] Started
[P] pipe is_open: 1
[P] Closing pipe...
[C] Terminating
[P] pipe is_open: 0
[P] Terminating
```

An you're right, there I need the bp::exe argument...

**Comment by mika-fischer** [comment] 2017-01-17 09:57
I think the problem is that you're not closing the write end of the pipe in the child process after forking. This is necessary, because as long as that's open, the pipe is open. If I close the fd in the child process by hand, things work as expected.

**Comment by mika-fischer** [comment] 2017-01-17 10:01
Similarly, the parent should close the read end after forking...

**Comment by klemens-morgenstern** [comment] 2017-01-17 12:35
It seems you're right, that's actually rather obvious. Interestingly that really worked on my Debian VM, no clue why. I'll wait for the test to cycle and then merge it, thank you!

**Comment by klemens-morgenstern** [comment] 2017-01-17 15:02
So I've merged it into develop, it would be awesome if you could test this. If that solves your problem, I'll push it into the boost repository as well.

**Comment by mika-fischer** [comment] 2017-01-17 15:26
Awesome, thanks a lot! Yes, I can confirm that your changes fixed the issue for me.

**Closed** 2017-01-22 11:43 UTC
