### ISSUE TITLE
Issue building small example program on MSVC with multiple compilers

### ISSUE THREAD

**Issue by emmenlau** [klemens-morgenstern/boost-process#172] opened 2018-07-02 09:57 UTC
I wanted to report an issue building a small example program against boost 1.67.0 on MSVC. The build fails for me with several different compilers, with MSVC2015, MSVC2017, Intel Compiler, and MinGW-w64 from MSYS2. The build already fails in parsing the included headers. The errors pointed to a problem with the `boost::winapi`definition. I tracked down the missing declaration of `WC_NO_BEST_FIT_CHARS_` into header `boost/winapi/character_code_conversion.hpp`. There is a check that seems to fail for me:
```
#if BOOST_USE_WINAPI_VERSION >= BOOST_WINAPI_VERSION_WIN2K
const DWORD_ WC_NO_BEST_FIT_CHARS_ = WC_NO_BEST_FIT_CHARS;
#endif
```
But I do not understand why it may fail because I have defines `/DWINVER=_WIN32_WINNT_WIN7 /D_WIN32_WINNT=_WIN32_WINNT_WIN7`. After a long search, I got boost.process working, but it required two additional defines:

```
#ifdef _WIN32
#define BOOST_USE_WINDOWS_H
#define WIN32_LEAN_AND_MEAN
#include <boost/process/windows.hpp>
#endif
#include <boost/process.hpp>
```
I wanted to share this insight. And of course it would be great if the issue can be fixed. However I may not be of much more help, because at this point I'm at the end of my wit what/why is failing.

In case it may be useful, these are the errors I got *without* the specific defines and includes above:
```
D:\Debug\Shared\include\boost/process/detail/windows/locale.hpp(81): error C2039: 'WC_NO_BEST_FIT_CHARS_': is not a member of 'boost::winapi'
D:\Debug\Shared\include\boost/winapi/character_code_conversion.hpp(44): note: see declaration of 'boost::winapi'
D:\Debug\Shared\include\boost/process/detail/windows/locale.hpp(81): error C2065: 'WC_NO_BEST_FIT_CHARS_': undeclared identifier
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(40): error C2079: 'boost::process::detail::windows::async_pipe::_source' uses undefined class 'boost::asio::windows::stream_handle'
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(41): error C2079: 'boost::process::detail::windows::async_pipe::_sink' uses undefined class 'boost::asio::windows::stream_handle'
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(57): error C2228: left of '.assign' must have class/struct/union
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(57): note: type is 'int'
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(58): error C2228: left of '.assign' must have class/struct/union
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(58): note: type is 'int'
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(91): error C2228: left of '.is_open' must have class/struct/union
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(91): note: type is 'int'
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(92): error C2228: left of '.cancel' must have class/struct/union
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(92): note: type is 'int'
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(93): error C2228: left of '.is_open' must have class/struct/union
D:\Debug\Shared\include\boost/process/detail/windows/async_pipe.hpp(93): note: type is 'int'
[...]
```
There where many more such issues but I truncate the list because it is repetitive after here.

**Comment by klemens-morgenstern** [comment] 2018-07-03 15:29
That looks bad, which OS are you working on?

**Comment by emmenlau** [comment] 2018-07-03 15:35
I'm working on Windows 7 x64. I don't know if this is related but I run my continuous integration from a Cygwin bash shell. The shell only orchestrates the build preparation, then calls cmd with a batch script that removes all references to Cygwin from the environment variables and the PATH before starting the build. I did never have problems with this approach, but it seems somehow boost::winapi is messed up for me unlesss I use
```
#define BOOST_USE_WINDOWS_H
#define WIN32_LEAN_AND_MEAN
```

**Comment by klemens-morgenstern** [comment] 2018-07-04 04:53
It does seem strange - I have appveyor running with win64 and MSVC though, so I am not sure what the issue is.

Does it work if you just include `<windows.h>` before `<boost/process.hpp>`?

**Comment by emmenlau** [comment] 2018-07-04 07:40
Nope, with just including `<windows.h>` it did not help, the error remains the same. I also tried explicitly defining `BOOST_USE_WINAPI_VERSION` to `_WIN32_WINNT_WIN7 ` but it did not help. So the error is quite mysterious. Since its inside the CI, I can not debug so easily. It would be interesting to see the preprocessor output but for me thats not easily accessible.
In any case, it works for me now. But it may be sensible to leave this issue hanging in case someone can reproduce (and provide more insight).

**Comment by klemens-morgenstern** [comment] 2018-07-04 07:45
Yeah no idea. Looks like something in winapi/asio though, I'll keep it open, maybe it's fixed in 1.68 already.

**Comment by sebkraemer** [comment] 2019-10-22 10:19
> ..> but it seems somehow boost::winapi is messed up for me unlesss I use
> 
> ```
> #define BOOST_USE_WINDOWS_H
> #define WIN32_LEAN_AND_MEAN
> ```

Same for me with VS 2019 (v142 toolchain), boost 1.69..

**Comment by emmenlau** [comment] 2020-01-30 13:47
This issue has not come up anymore since boost 1.70. @sebkraemer do you still experience this problem? Otherwise I'd like to close the issue.

**Comment by sebkraemer** [comment] 2020-02-01 20:22
I will check on Monday!

**Comment by klemens-morgenstern** [comment] 2022-06-11 05:34
I still don't know the solution, but it's probably an issue with boostorg/winapi. I think you could just define `BOOST_USE_WINDOWS_H`.

I'll close the issue, future issues will be at boostorg/process.

**Closed by klemens-morgenstern** 2022-06-11 05:34 UTC
