### ISSUE TITLE
Spurious failures when capturing process output

### ISSUE THREAD

**Issue by hotgloupi** [klemens-morgenstern/boost-process#22] opened 2016-09-23 15:38 UTC
I've managed to create a small example that reproduce the problem:

```
#include <boost/process.hpp>
#include <boost/asio.hpp>

#include <iostream>

namespace bp = boost::process;

int main()
{
    // We will start 10 concurrent processes
    std::vector<
        std::pair<
            std::shared_ptr<bp::child>,
            std::future<std::string>
        >
    > processes;
    processes.resize(10);

    // Let's setup a simple timer
    boost::asio::io_service io_service;
    boost::posix_time::milliseconds interval(1000);
    boost::asio::deadline_timer timer(io_service, interval);

    std::function<void(boost::system::error_code const& ec)> update_cb;

    update_cb = [&](boost::system::error_code const& ec) -> void {
        if (ec) return;
        for (auto& p: processes)
        {
            // The process can be launched
            if (p.first == nullptr)
            {
                p.first = std::make_shared<bp::child>(
                    "/bin/sh", "-c", "echo \"hello, world!\"",
                    bp::std_in.close(),
                    bp::std_err.close(),
                    bp::std_out > p.second,
                    io_service
                );
            }
            else if (!p.first->running()) // The process has finished
            {
                std::string out = p.second.get();
                std::cout << "got result: '" << out << "'\n";
                assert(!out.empty()); // <-- should never abort, but does...
                p.first.reset();
            }
        }
        timer.expires_at(timer.expires_at() + interval);
        timer.async_wait(update_cb);
    };

    timer.async_wait(update_cb);
    io_service.run();
    return 0;
}
```

On my platform (centos 6), this is what I got:

```
$  ./a.out
got result: 'hello, world!
'
got result: 'hello, world!
'
got result: 'hello, world!
'
got result: 'hello, world!
'
got result: 'hello, world!
'
got result: 'hello, world!
'
got result: 'hello, world!
'
got result: ''
a.out: test.cpp:44: main()::__lambda24: Assertion `!out.empty()' failed.
Aborted (core dumped)

```

Did I do something wrong ?

**Comment by klemens-morgenstern** [comment] 2016-09-23 16:34
Just fyi: `child` is movable and has a default-ctor, so you do not need the shared_ptr there.

Otherwise: no clue what's wrong there, it looks correct to me. I also wouldn't know why the eight process fails when it's launched exactly the same way. Does the same thing happen if you use `bp::on_exit` to get the result?

**Comment by hotgloupi** [comment] 2016-09-24 15:12
I don't think that any of the process fails, if you add a check on exit_code(), it is correctly always equal to 0. I will have access to my machine monday if you need me to test something more.

Did you try to run this small program on your env ? does it work reliably ?

**Comment by klemens-morgenstern** [comment] 2016-09-24 16:30
I did not, but I guess that's a good test. I'll add it as a test soon and tell you what happens. Might be a few days still, I just found a few bugs lately, so there's still other urgent stuff to do.

**Comment by klemens-morgenstern** [comment] 2016-09-25 15:29
Tested that on windows with gcc 6, works there (10 * 100 processes). 
On linux (Debian x64 VM) I get the same error, which strangely enough only fails for the last of the group being launched. However: if I put a sleep(20) behind the launch of the process it works. So I guess this is some strange problem with the OS; I really have no idea. Maybe it blocks when to maby processes are launched at once - but then I would've expected it to fail after a fixed number of processes, not just for the last one.

**Comment by klemens-morgenstern** [comment] 2016-10-09 21:49
I´m closing this now, since I think it is justified to assume, that it`s a system limit, since I can fix it with `sleep(20)`.

**Comment by hotgloupi** [comment] 2016-10-11 10:18
I don't think that's a system limit, as the problem appears when spawning 10 processes. As the sample program I crafted to reproduce the seems perfectly valid, it sounds strange to me that you want to left this as is. It must be some ordering issue between the closing of the process and the reading of the pipes. IMHO, losing randomly some output data is quite critical.

**Comment by klemens-morgenstern** [comment] 2016-10-11 11:08
Well the problem is, that we´ve got no idea on what is happening here. Though there might be another explanation come to think of it:

The way the async_io works is that it closes the pipe asynchronously, by posting it onto the io_service. I.e.:

```cpp
asio::io_service ios;
asnyc_pipe p(ios);
bp::child c(..., on_exit([&](...){ios.post([&]{p.close();});}));
```

This does give the io_service time to check if there's any input on the pipe before closing is and the assumption is that the posted function will be executed afterwards. This could be a race condition here and would explain why it works with a `sleep(20)`. But I don't know how that could be fixed - without a timeout that is, as I despise arbitrary delays. And before you ask, I can't use `FD_CLOEXEC` because I've got no equivalent on windows (for named pipes that is).

I'll need to try that to find out if it might be the issue, but that may take a while. If you want to help me out there, just put modify `detail/posix/async_out.hpp:157-161` to use a timer.

**Comment by klemens-morgenstern** [comment] 2016-10-15 14:55
@hotgloupi Thanks for insisting, it indeed has nothing to do with the multiple problems, but with the fact that the pipe buffer doesn't work fast enough. I was able to reproduce the error with this code:

```cpp
BOOST_AUTO_TEST_CASE(async_fast_fut, *boost::unit_test::timeout(2))
{
    boost::asio::io_service ios;

    bp::child c;
    std::future<std::string> fut;

    ios.post([&]
              {
                    c = bp::child("echo test string", bp::shell,
                                  bp::std_out > fut, ios);
              });

    ios.run();
    BOOST_CHECK(fut.valid());
    BOOST_CHECK(boost::algorithm::starts_with(fut.get(), "test string"));
}
```

Hopefully there's an easy solution for that.

**Comment by klemens-morgenstern** [comment] 2016-10-15 17:25
Sooo, I had the same problem when using synchronous I/O I could even reproduce it in the shell. That is:
```
klemens@debian:~/boost/libs/process/test$ /bin/sh -c echo hello world && echo thingy

thingy
klemens@debian:~/boost/libs/process/test$
```

It's an issue with echo, not with the library. Same thing when redirecting it to a file. The question should rather be why it works with the other cases in the first place.

**Comment by hotgloupi** [comment] 2016-11-04 16:12
No, it's not an "issue with echo", you just got the quotes wrong. If you do:

    $ /bin/sh -c echo a b c d
    
    $

You'll see that every argument after `echo` is ignored. whereas,

    $ /bin/sh -c "echo a b c d"
    a b c d

Does the correct thing. So your test is equivalent to:

    $ /bin/sh -c "echo" && echo thingy

where `/bin/sh -c "echo"` and `echo thingy` are executed one after the other. With the correct quoting:

    $ /bin/sh -c "echo 'hello world' && echo 'thingy'"
    hello world
    thingy
    $

Anyway, echo is a builtin, you might want to use a real binary to get something portable.

**Comment by klemens-morgenstern** [comment] 2016-11-04 17:34
I see, though it's strange enought that the latter part was echoed. Thing is: I have a few tests with a binary where it works quite reliable; that is what made me sceptical of that.
However, the asnyc_pipe will get a slight change in the way it handles the exit notifications, so that might fix the issue. I'll let you know when I've got news there.

**Comment by hotgloupi** [comment] 2016-11-04 19:21
No worries :)

Just so you know, the last part was echoed because the first part didn't fail, as if you did

    $ true && echo something

whereas the following does not print anything:

    $ false && echo something

In any case, you might want to re-open the issue since it is not fixed.

**Comment by klemens-morgenstern** [comment] 2016-11-04 19:33
Alright then. I'll have news next week, I'll work on the pipe stuff after the review ends.

**Closed** 2016-12-05 20:20 UTC
